name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Build Docker image
      run: docker build -t solution .
      
    - name: Run tests
      run: docker run --entrypoint pytest solution test_compute.py -v 